version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    version_requirement_updates: "off"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "all"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "in_range"
